name: "Bug Report"
description: Report a bug.
title: "fix: <title>"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Bug description.
      placeholder: Please enter an description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Reproduction Steps"
      description: Steps to reproduce the bug.
      placeholder: Please enter the steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: "Additional Information"
      description: Any additional information you would like to add.
      placeholder: Any additional information you would like to add.
    validations:
      required: false
